# Generated by Django 2.0.5 on 2018-07-14 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportsgramapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_name', models.CharField(max_length=50)),
                ('ground_image', models.ImageField(blank=True, null=True, upload_to='grounds_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_message', models.TextField(blank=True)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='uploaded_media')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('verified', models.BooleanField(default=False)),
                ('display_picture', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('grounds', models.ManyToManyField(blank=True, to='sportsgramapp.Ground')),
                ('location', models.ManyToManyField(blank=True, to='sportsgramapp.Location')),
            ],
        ),
        migrations.AddField(
            model_name='sport',
            name='sport_image',
            field=models.ImageField(blank=True, null=True, upload_to='sports_images/'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sports',
            field=models.ManyToManyField(blank=True, to='sportsgramapp.Sport'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ground',
            name='ground_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsgramapp.Location'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsgramapp.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
