# Generated by Django 2.0.5 on 2018-07-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsgramapp', '0002_auto_20180714_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='match_dateTime',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
